### ISSUE TITLE
ТЗ

### ISSUE THREAD

**Issue by Roonya04** [Roonya04/CoursePaper#1]
Техническое задание
1.1 Общие сведения:
1.1.1 Полное наименование системы: 
**Платформа обратной связи администрации с населением**
1.1.2 Наименование организации - заказчика, разработчика системы:
Заказчик: КФ МГТУ им. Н. Э. Баумана 
Разработчик: Студентка КФ МГТУ им Н. Э. Баумана группы ИУК5-52Б Мельникова В.Д.
1.1.3 Плановые сроки начала и окончания работы по созданию системы:
Плановый срок начала работ - 
Плановый срок окончания работ - 
1.2 Назначение и цели создания системы:
1.2.1 Назначение системы: 
Сервис предназначен для администрации города и его жителей. Он предоставляет возможность:
Жителям: выражать мнения, предложения и жалобы по местным вопросам, 
Сотрудникам администрации: улучшить взаимодействие с населением и повысить эффективность работы.
1.2.2 Цели системы:
Повышение оперативности взаимодействия между органами местного самоуправления и населением.
1.3 Требования к системе
1.3.1 Требования к системе в целом: 
1.3.1.1 Требования к структуре и функционированию системы: 
Система разделена на 2 подструктуры:
1.Клиентская часть в виде веб-платформы обратной связи 
2.Место хранения данных (база данных)
1.3.1.2 Требования по эргономике и технической эстетике:
Интерфейс системы не должен вводить пользователя в заблуждение, содержать элементы, назначение которых не очевидно или элементы, функционал которых отсутствует или не соответствует пояснению в интерфейсе.
Интерфейс должен быть понятен и не перегружен графическими элементами.
1.3.2 Требования к функциям (задачам), выполняемым системой
	Авторизация на сайте
	Написание заявления
	Просмотр статуса заявления
	Просмотр ответственного за решение проблемы         
	Анализ и добавление проблем в реестр
	Управление статусами и отслеживание
	Анализ данных и отчетность
1.3.3 Требования к видам обеспечения 
1.3.3.1 Требования к лингвистическому обеспечению системы 
Средством описания предметной области, также как и средством взаимодействия Пользователя с системой является русский язык. 
1.3.3.2 Требования к входным и выходным данным 
Входными данными системы от Пользователей приложения являются логин и пароль, их обращения. Выходными данными являются уникальный номер обращения, его статус и ответное сообщение от сотрудника.
1.3.3.3 Требования к программному обеспечению системы
Для разработки сервиса используются HTML5, CSS, JavaScript, для работы с СУБД - MySQL. 
1.4 Состав и удержание работ по созданию (развитию) системы
1.Утверждение темы, задания на разработку, технического задания (альфа). Оформление ТЗ. Описание предметной области и требований к системе. Концептуальная схема. Прототип или скетчи интерфейса.
2.Оформление введения исследовательской части. Обоснование выбора БД, логическая схема БД, физическая схема данных. Демонстрация работы макета системы с БД.
3.Оформление проектно-конструкторской части. Демонстрация работающего приложения. Презентация (альфа). Тестирование и отладка приложения. Разработка эксплуатационной документации.
4.Завершающее оформление документации согласно требованиям ГОСТ. Все ошибки и проблемы устранены. Подготовка доклада. Защита курсовой работы.
1.5 Порядок контроля и приемки системы
Система разрабатывается с применением тестирования работоспособности функционала. При добавлении новых функций предыдущие тесты должны сохранять работоспособность. Приемка работы осуществляется комиссией КФ МГТУ им. Н. Э. Баумана кафедры ИУК5.
1.6 Требования к документированию
Требуется предоставить:
а. Техническое задание в соответствии с ГОСТ 34.602-89
b. Расчетно-пояснительную записку, включающую исследовательскую часть, проектно-конструкторскую часть и проектно-технологическую часть, включающую в себя руководство пользователя и руководство программиста (администратора).
Расчетно-пояснительная записка выполняется с учетом требований, предусмотренных ГОСТ 7.32-2001 и 2.105-95.

**Comment by wldmr-key** [comment]
у тебя в системе как минимум две роли. Нужно их описать, конечно. И, очевидно, для разных ролей будут разные функции. Желательно описание объекта автоматизации - как построена работа с обращениями без твоей системы?

**Comment by Roonya04** [comment]
@wldmr-key 
А где именно указывать роли и "как построена работа с обращениями без твоей системы" ?

**Comment by wldmr-key** [comment]
в требованиях к функциям - типа: система должна обеспечивать работу следующих типов пользователей: ...

Объектом автоматизации является процесс работы с жалобами и обращениями граждан ...., который включает в себя ... (и дальше - что происходит с этими жалобами)

**Comment by Roonya04** [comment]
@wldmr-key 
Получилось как-то так

1.3.2 Требования к функциям (задачам), выполняемым системой
Система должна обеспечивать работу следующих типов пользователей:
Житель:
o	Регистрация и авторизация
o	Написание заявлений
o	Просмотр статуса обращения
o	Просмотр ответственного за решение проблемы
Сотрудник администрации:
o	Авторизация
o	Анализ и добавление проблем в реестр
o	Управление статусами и отслеживание
Объектом автоматизации является процесс работы с жалобами и обращениями граждан. Этот процесс включает в себя подачу обращения. Далее следуют регистрация обращения, его распределение. После этого специалист администрации приступает к обработке обращения. Наконец, после решения проблемы обращение закрывается, и информация о статусе передается жителю.

**Comment by wldmr-key** [comment]
неплохо. А контроль за сотрудниками осуществляется? Или они все белые и пушистые? А нормы на рассмотрение есть? "Управление статусами и отслеживание" - это как?

Требования к входным и выходным данным - подумай... На мой взгляд, несколько не то...

**Comment by Roonya04** [comment]
@wldmr-key 
 А контроль за сотрудниками осуществляется? Или они все белые и пушистые? - **Думаю, контроля нет. Пусть будут белые и пушистые)**
 А нормы на рассмотрение есть? - **Если только какие-нибудь временные, больше никаких норм в голову не приходят**
 "Управление статусами и отслеживание" - это как? - **Сотрудник, когда начинает работу над обращением, меняет его статус = Управление, ну а отслеживать же они тоже могут, сколько в работе, сколько уже закончено**
 
 
 Насчет данных, я вновь разделила их на жителей и сотрудников. 
 1.3.3.2 Требования к входным и выходным данным 
   Входные данные:
      Житель:
      •	        Логин, пароль
      • 	Обращение
      Сотрудник администрации:
      • 	Логин, пароль
      • 	Ответ на обращение
      • 	Статус обращения
    Выходные данные:
      Житель:
      • 	Ответ на обращение от сотрудника
      • 	Статус обращения
      Сотрудник администрации:
      • 	Список обращений

**Comment by wldmr-key** [comment]
`Думаю, контроля нет. Пусть будут белые и пушистые)` - не согласен. Вот тебе кейс - я пожаловался тебе. Ты ответила и пошла в отпуск. А я хочу продолжить разговор (уточнить, поправить, да, что угодно). Кто мне ответит?
Да, и оценивать работу сотрудников нужно

`А нормы на рассмотрение есть? - Если только какие-нибудь временные` - да, именно они, причем, они установлены законами

`"Управление статусами и отслеживание" - это как?` - лучше хорошо обдумать и уточнить прямо в ТЗ

**Comment by Roonya04** [comment]
> Кто мне ответит?

Тот, кто встанет на место того сотрудника, который ушел в отпуск.
А оценка работы будет в "отзывах" так называемых

Про нормы не знала, буду уточнять. В каком пункте указываются нормы времени?

А если вместо "Управление статусами и отслеживание" указать вот так:
o	Изменение статуса обращения
o	Отслеживание сроков обработки

Входные и выходные данные получились? Или всё-таки не очень?

**Comment by wldmr-key** [comment]
хм...

`В каком пункте указываются нормы времени?`
Тебе явно не хватает описания объекта автоматизации - как происходит работа с обращениями без твоей системы. Тогда многое бы стало яснее...

Как обращения делятся между сотрудниками? Как ты считаешь, сколько их примерно (сотрудников)? Они смотрят на все-все обращения?

`А если вместо "Управление статусами и отслеживание" указать вот так:` - прежде всего, непонятно что такое статусы в твоем понимании и какие они бывают?

`Входные и выходные данные получились? Или всё-таки не очень?` - сойдет, хотя, как правило, интерактивные данные (особенно логины/пароли) крайне редко пишутся во входных/выходных данных (и так понятно из функций). Чаще здесь пишутся данные внешних систем, так что можешь смело опустить этот раздел

**Comment by Roonya04** [comment]
**_Тебе явно не хватает описания объекта автоматизации_** - так я выше его указывала, просто не изменяла в самом начале... Следующим отправлю то, что у меня вышло в итоге. 

**_Как обращения делятся между сотрудниками? Как ты считаешь, сколько их примерно (сотрудников)? Они смотрят на все-все обращения?_** - Вообще, я думала да. Все сотрудники смотрят на все обращения. Думаю, редко встретишь человека кто бы захотел забрать больше работы на себя (забрать обращение не из его категории). Сотрудников, думаю, будет не сильно много. Они как раз-таки обращались бы в нужные организации для решения проблемы.

 **_прежде всего, непонятно что такое статусы в твоем понимании и какие они бывают?_** - Статус может быть, например, "Принято в работу", "Решено", "Отклонено" и тд
 
 Получается раздел с входными и выходными данными просто убрать?

**Comment by Roonya04** [comment]
1.Техническое задание
1.1 Общие сведения:
1.1.1 Полное наименование системы: 
Платформа обратной связи администрации с населением
1.1.2 Наименование организации - заказчика, разработчика системы:
Заказчик: КФ МГТУ им. Н. Э. Баумана 
Разработчик: Студентка КФ МГТУ им Н. Э. Баумана группы ИУК5-52Б Мельникова В.Д.
1.1.3 Плановые сроки начала и окончания работы по созданию системы:
Плановый срок начала работ - 
Плановый срок окончания работ - 
1.2 Назначение и цели создания системы:
1.2.1 Назначение системы: 
Сервис предназначен для администрации города и его жителей. Он предоставляет возможность:
Жителям: выражать мнения, предложения и жалобы по местным вопросам, 
Сотрудникам администрации: улучшить взаимодействие с населением и повысить эффективность работы.
1.2.2 Цели системы:
Повышение оперативности взаимодействия между органами местного самоуправления и населением.
1.3 Требования к системе
1.3.1 Требования к системе в целом: 
1.3.1.1 Требования к структуре и функционированию системы: 
Система разделена на 2 подструктуры:
1.Клиентская часть в виде веб-платформы для обратной связи
2.Место хранения данных (база данных)
1.3.1.2 Требования по эргономике и технической эстетике:
Интерфейс системы не должен вводить пользователя в заблуждение, содержать элементы, назначение которых не очевидно или элементы, функционал которых отсутствует или не соответствует пояснению в интерфейсе.
Интерфейс должен быть понятен и не перегружен графическими элементами.
1.3.2 Требования к функциям (задачам), выполняемым системой
Система должна обеспечивать работу следующих типов пользователей:
Житель:
o	Регистрация и авторизация
o	Написание заявлений
o	Просмотр статуса обращения
o	Просмотр ответственного за решение проблемы
Сотрудник администрации:
o	Авторизация
o	Анализ и добавление проблем в реестр
o	Изменение статуса обращения
o	Отслеживание сроков обработки
Объектом автоматизации является процесс работы с жалобами и обращениями граждан. Этот процесс включает в себя подачу обращения. Далее следуют регистрация обращения, его распределение. После этого специалист администрации приступает к обработке обращения. Важно отметить, что для каждого типа обращений установлены конкретные сроки обработки. Наконец, после решения проблемы обращение закрывается, и информация о статусе передается жителю.
1.3.3 Требования к видам обеспечения 
1.3.3.1 Требования к лингвистическому обеспечению системы 
Средством описания предметной области, так же как и средством взаимодействия Пользователя с системой является русский язык. 
1.3.3.2 Требования к входным и выходным данным 
Входные данные:
Житель:
•	Логин, пароль
•	Обращение
Сотрудник администрации:
•	Логин, пароль
•	Ответ на обращение
•	Статус обращения
Выходные данные:
Житель:
•	Ответ на обращение от сотрудника
•	Статус обращения
Сотрудник администрации:
•	Список обращений
1.3.3.3 Требования к программному обеспечению системы
Для разработки сервиса используются HTML5, CSS, JavaScript, для работы с СУБД - MySQL. 
1.4 Состав и удержание работ по созданию (развитию) системы
1.Утверждение темы, задания на разработку, технического задания (альфа). Оформление ТЗ. Описание предметной области и требований к системе. Концептуальная схема. Прототип или скетчи интерфейса.
2.Оформление введения исследовательской части. Обоснование выбора БД, логическая схема БД, физическая схема данных. Демонстрация работы макета системы с БД.
3.Оформление проектно-конструкторской части. Демонстрация работающего приложения. Презентация (альфа). Тестирование и отладка приложения. Разработка эксплуатационной документации.
4.Завершающее оформление документации согласно требованиям ГОСТ. Все ошибки и проблемы устранены. Подготовка доклада. Защита курсовой работы.
1.5 Порядок контроля и приемки системы
Система разрабатывается с применением тестирования работоспособности функционала. При добавлении новых функций предыдущие тесты должны сохранять работоспособность. Приемка работы осуществляется комиссией КФ МГТУ им. Н. Э. Баумана кафедры ИУК5.
1.6 Требования к документированию
Требуется предоставить:
а. Техническое задание в соответствии с ГОСТ 34.602-89
b. Расчетно-пояснительную записку, включающую исследовательскую часть, проектно-конструкторскую часть и проектно-технологическую часть, включающую в себя руководство пользователя и руководство программиста (администратора).
Расчетно-пояснительная записка выполняется с учетом требований, предусмотренных ГОСТ 7.32-2001 и 2.105-95.

**Comment by wldmr-key** [comment]
в таком виде задание безусловно можно печатать и сдавать в качестве отчета по практике. Но по существу пока я по-прежнему считаю самым слабым местом твоего плана отсутствие автоматизации распределения обращений и контроля исполнения

**Comment by Roonya04** [comment]
Я решила выделить прям отдельный тип пользователя "Специалист по автоматизации и аналитике обращений", дав ему ряд функций.
И поменяла немного объект автоматизации.

1.3.2 Требования к функциям (задачам), выполняемым системой
Система должна обеспечивать работу следующих типов пользователей:
Житель:
o	Регистрация и авторизация
o	Написание заявлений
o	Просмотр статуса обращения
o	Просмотр ответственного за решение проблемы
Сотрудник администрации:
o	Авторизация
o	Анализ и добавление проблем в реестр
o	Изменение статуса обращения
o	Отслеживание сроков обработки
Специалист по автоматизации и аналитике обращений: 
o	Контроль над сотрудниками
o	Распределение обращений
o	Анализ данных о обращениях 
o	Консультирование сотрудников администрации
Объектом автоматизации является процесс работы с жалобами и обращениями граждан. Житель подает обращение через систему. Обращение регистрируется в системе. Специалист распределяет обращение по категориям, направляя его нужному сотруднику. Сотрудник администрации приступает к обработке обращения и изменяет статус обращения (например, "Принято в работу", "Решено", "Отклонено" и т.д.) по мере его обработки. После решения проблемы жителю направляются информация о статусе его обращения и ответное сообщение. Весь процесс контролируется отдельным специалистом, который следит за соблюдением сроков и качеством обработки обращений.  

**После занятия возникло сомнение насчет назначения. Могу ли я оставить его таким:**
1.2.1 Назначение системы:
Сервис предназначен для администрации города и его жителей. Он предоставляет возможность:
Жителям: выражать мнения, предложения и жалобы по местным вопросам,
Сотрудникам администрации: улучшить взаимодействие с населением и повысить эффективность работы.
**Или исправить на:**
1.2.1 Назначение системы:
Сервис предназначен для администрации города.

**Comment by wldmr-key** [comment]
блеск!
