### ISSUE TITLE
Исследовательская часть

### ISSUE THREAD

**Issue by Roonya04** [Roonya04/CoursePaper#10]
**1.	Постановка задачи проектирования.** 
Она должна быть как в тз цель или вот такая:
=============================
Создание удобного и интуитивно понятного интерфейса для пользователей.
Реализация функционала, позволяющего жителям:
- Регистрироваться и авторизовываться.
- Оставлять заявления.
- Просматривать статус обращения.
- Видеть ответственного за решение проблемы.
Реализация функционала, позволяющего сотрудникам администрации:
- Авторизовываться.
- Анализировать и добавлять проблемы в реестр.
- Изменять статус обращения.
- Отслеживать сроки обработки.
Реализация функционала, позволяющего специалистам по автоматизации и аналитике обращений:
- Контролировать сотрудников.
- Распределять обращения.
- Анализировать данные о обращениях.
- Консультировать сотрудников администрации.

**2.	Описание предметной области.**
В другом issue

**3.	Анализ аналогов.**
В другом issue

**4.	Перечень задач, подлежащих решению в процессе разработки.**
1)	Ввод и просмотр данных:
•	Регистрация и авторизация пользователей.
•	Создание и просмотр заявлений.
•	Просмотр статуса обращения.
•	Просмотр ответственного за решение проблемы.
2)	Редактирование и удаление существующих данных:
•	Управление статусами обращений.
•	Анализ и добавление проблем в реестр.
•	Контроль и распределение обращений.
3)	Доступ нескольких типов пользователей:
•	Разграничение прав доступа для жителей, сотрудников администрации и специалистов по автоматизации и аналитике обращений.
4)	Разработка концепции пользовательского интерфейса:
•	Создание удобного и интуитивно понятного интерфейса для всех типов пользователей.
5)	Разработка концепции отображения содержимого:
•	Определение структуры и дизайна страниц сайта.
6)	Проектирование базы данных:
•	Создание схемы базы данных для хранения информации о пользователях, обращениях и т.д.
7)	Разработка хранимых SQL-процедур:
•	Создание хранимых процедур для выполнения сложных запросов к базе данных.
8)	Разработка триггеров:
•	Создание триггеров для автоматизации выполнения определенных действий при изменении данных в базе.

**5.	Обоснование выбора инструментов и платформы для разработки.**
Современные сайты должны быть интерактивными, позволять пользователям регистрироваться, получать нужную им информацию и т.д., причем перечень интерактивных возможностей сайтов постоянно растет. Естественно, что 8 возможностей языка HTML недостаточно, для того, чтобы создавать подобные сайты и следует использовать дополнительные средства. 
Очень большое распространение получили бесплатные системы управления контентом. Большинство этих систем имеет хорошее качество исполнения и высокую надежность, что дает им большое преимущество среди других систем. А технологии добавления контента популярных бесплатных CMS не отличается от платных, что только делает их более популярными среди создателей сайтов. 
Аббревиатура CMS расшифровывается как «Content Management Software» («программное обеспечение для управления содержимым»). 
Система управления сайтами – это программный комплекс, позволяющий автоматизировать процесс управления как сайтом в целом, так и сущностями в рамках сайта. 
Одни из известных систем Drupal, Joomla и WordPress - системы управления, на основе которых можно создавать функциональные и легко управляемые сайты без серьезных финансовых затрат. 
Так как администрированием после внедрения сайта будет заниматься сотрудник администрации из существенных недостатков известных CMS систем можно выделить: 
1. Drupal: 
a. Сложный для восприятия интерфейс. 
b. Высокие технические требования к серверу. 
c. Отсутствие технической поддержки для пользователей. 
d. Отсутствие файлового менеджера в режиме администратора. 
2. Wordpress. 
a. Достаточно сложная панель управления. 
b. Есть минусы при SEO-оптимизации сайта в работе с title и заголовками, появляются дубли при редактировании страниц. 
c. Было замечено, что сайты на Джумле грузятся медленнее, чем на других CMS.
В ходе рассмотрения систем управления особых минусов не было выделено у CMS Joomla. Было принято решение использовать эту систему в разработке платформы обратной связи администрации с населением. Коротко о системе можно сказать, что на сегодняшний день она наиболее популярна. Joomla является свободным программным обеспечением, распространяемым под лицензией GNUGPL. Система управления контентом (CMS) написана на языках РНР и JavaScript. В качестве хранилища использует базы данных MySQL

**Comment by wldmr-key** [comment]
`Она должна быть как в тз цель или вот такая:` - не как в ТЗ. В ТЗ ты пишешь задание на систему, а здесь - на исследование. Поэтому, задача (не создание интерфейса, конечно) - выполнить проектирование, а именно: описать, что ты должна сделать в исследовании - описать предметную область, уточнить требования к данным системы, исследовать аналоги, составить модель данных и что-там-у-тебя-еще...

**Comment by Roonya04** [comment]
**Переписала задачу, стало выглядеть так:**

Исследовать предметную область: 
изучить текущие процедуры приема, обработки и ответа на обращения жителей в администрацию, выявить их недостатки и точки роста. Определить основные группы пользователей системы (жители, сотрудники администрации, специалисты по автоматизации и аналитике) и проанализировать их потребности и ожидания. Изучить законодательство, регулирующее процесс обращения граждан в органы власти, и выявить требования к системе.
Уточнить требования к системе: 
определить функциональные требования для каждой группы пользователей, включая регистрацию и авторизацию, создание и отправку заявлений, просмотр статуса обращения, анализ данных о обращениях и т.д.
Исследовать аналоги: 
провести анализ существующих решений на рынке, предоставляющих функционал электронных обращений в органы власти. Выявить преимущества и недостатки аналогов. Определить возможность использования готовых решений или их компонентов в рамках проекта.
Спроектировать модели данных: 
разработать концептуальную модель данных, описывающую основные сущности системы. Создать логическую модель данных, определяющую структуру таблиц, связи между ними и типы данных. Разработать физическую модель данных, учитывающую особенности выбранной СУБД.
Обосновать выбор инструментов и платформы для разработки:
обосновать выбор системы управления базами данных и инструментов для разработки пользовательского интерфейса, обеспечивающих создание удобного и интуитивно понятного интерфейса для всех групп пользователей.

**А что насчет 4 и 5 пунктов? выглядят адекватно?**

**Comment by wldmr-key** [comment]
вполне!

**Comment by Roonya04** [comment]
Спасибо!
