### ISSUE TITLE
Концептуальная модель данных

### ISSUE THREAD

**Issue by Roonya04** [Roonya04/CoursePaper#6]
![КонцМодДанных](https://github.com/user-attachments/assets/3997018b-21b8-465f-80c2-5a595427d396)

**Comment by wldmr-key** [comment]
для оценки не хватает скорректированного описания предметной области. Кстати, а что происходит, если об одной проблеме сообщает несколько человек (если в кране нет воды...)?

**Comment by Roonya04** [comment]
![image](https://github.com/user-attachments/assets/c5224eb7-3f91-4d29-b44b-cc7636662c6c)

Не получилось учесть наличие специалиста, который все контролирует

**Comment by wldmr-key** [comment]
я бы предложил (предварительно описав это в требованиях к системе) назначить сотрудникам роли (и, возможно, асоциировав их с категориями - скажем, Иванова и Петров отвечают на обращения по ЖКХ, а Онопко контролирует исполнение обращений по ЖКХ)

**Comment by Roonya04** [comment]
![image](https://github.com/user-attachments/assets/fe4847e7-efe1-4c95-91e9-71c73d907722)

получилось как-то так. 
Убрали атрибут должность в сотрудниках, тк, думаю, роль - это одно и то же

**Comment by wldmr-key** [comment]
норм. А, как насчет  `(предварительно описав это в требованиях к системе) ` ?
